abstract final class AppAssets {
  static const bg = 'assets/figma/bg.png';
  static const hero = 'assets/figma/hero.png';
  static const rewardOne = 'assets/figma/reward_1.png';
  static const rewardTwo = 'assets/figma/reward_2.png';
  static const freeReward = 'assets/figma/free_reward.png';
  static const premiumReward = 'assets/figma/premium_reward.png';
  static const reference = 'assets/figma/battle_pass_reference.png';
  static const clock = 'assets/figma/clock.svg';
  static const close = 'assets/figma/close.svg';
  static const done = 'assets/figma/done.svg';
  static const navBackground = 'assets/figma/nav/background.png';
  static const navEvent = 'assets/figma/nav/event.svg';
  static const navBattlePass = 'assets/figma/nav/battle_pass.svg';
  static const navCalendar = 'assets/figma/nav/calendar.svg';
  static const navAfter = 'assets/figma/nav/after.svg';
  static const navInvite = 'assets/figma/nav/invite.svg';
  static const navPromo = 'assets/figma/nav/promo.svg';
  static const xp = 'assets/figma/xp.png';
  static const tasks = 'assets/figma/tasks.svg';
  static const premium = 'assets/figma/icn_premium.svg';
  static const info = 'assets/figma/icn_info_fill.svg';
  static const arrowLeft = 'assets/figma/arrow_left.svg';
  static const arrowRoad = 'assets/figma/arrow_road.svg';
}
